server:
  port: 8081
---
#spring:
#  datasource:
#    password: mysql
#    url: jdbc:mysql://localhost:3306/orders
#    username: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect # MySQL5InnoDBDialect
#    show-sql: true # not recommended for production
#  data:
#    rest:
#      base-path: /api
spring:
  h2: # http://localhost:8081/h2-console
    console:
      enabled: true
      settings:
        web-allow-others: true # for remote access    
  datasource:
    name: orders
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:~/orders-db;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop # update, create, create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  data:
    rest:
      base-path: /api
      