server:
  port: 8081

spring:
  datasource:
    password: mysql
    url: jdbc:mysql://localhost:3306/orders
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect # MySQL5InnoDBDialect
    show-sql: true # not recommended for production
  data:
    rest:
      base-path: /api
